# Generated by Django 3.1.4 on 2021-01-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210101_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_detail',
            old_name='Applicants_image',
            new_name='A_image',
        ),
        migrations.RenameField(
            model_name='loan_detail',
            old_name='Address',
            new_name='add',
        ),
        migrations.RenameField(
            model_name='loan_detail',
            old_name='Aname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='loan_detail',
            old_name='user_exists',
            new_name='u_exists',
        ),
    ]
