# Generated by Django 3.1.4 on 2021-01-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_loan_detail_loan_approve'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loan_detail',
            new_name='loan_data',
        ),
    ]
