# Generated by Django 3.1.4 on 2021-01-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_auto_20210101_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_data',
            name='loan_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
