# Generated by Django 3.1.4 on 2021-01-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Acount_number', models.IntegerField(unique=True)),
                ('PIN', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('mob', models.IntegerField(unique=True)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Administrative',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('mob', models.IntegerField(unique=True)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Offeres',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('desc', models.CharField(max_length=5000)),
                ('pic', models.ImageField(upload_to='events/')),
                ('offerend', models.DateTimeField()),
            ],
        ),
    ]
