# Generated by Django 3.1.4 on 2021-01-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovaScotia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_approved_user',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('loan_type', models.CharField(max_length=100)),
                ('loan_amount', models.FloatField(default=100000)),
                ('years', models.IntegerField(default=1)),
                ('EMI', models.FloatField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('mob', models.IntegerField(unique=True)),
                ('rate', models.FloatField(default=7)),
            ],
        ),
    ]
