# Generated by Django 3.1.4 on 2021-01-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovaScotia', '0003_loan_approved_user_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_approved_user',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
