# Generated by Django 3.1.4 on 2021-01-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovaScotia', '0007_auto_20210102_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeres',
            name='offerend',
        ),
    ]
